redis.enable.embedded=false
dev.mode=true
filestore.base.dir=C:\\Temp\\Odisha

#Enable or Disable Multitenancy
multitenancy.enabled=true

#Tenant Configuration
state.schema.name=state
tenant.state.odisha.local.org=state
tenant.ulb.odisha.local.org=generic
common.domain.name=odisha.local.org

#Elastic Search Configuration
elasticsearch.hosts=localhost
elasticsearch.port=9300
elasticsearch.cluster.name=elasticsearch-Reza


#--------------------------MDMS-------------------------------------------------------------------#
mdms.enable=true
#mdms.host=http://40.80.83.210:8094
mdms.host=https://sujog-dev.odisha.gov.in
#--------------------------MDMS Ends-------------------------------------------------------------------#
#-- LOGO---#
#ulb.logo.uri=https://digitaldesksujog051120.blob.core.windows.net/assets/Logos/odlogo.png
#ulb.logo.uri=https://digitaldesksujog051120.blob.core.windows.net/assets/Logos/ULB.png

#filestoreservice.beanname=egovMicroServiceStore
ms.url=http://localhost:8060/

download.url.support.flage=false
collection-services.host=

egov.collection.service.host=https://sujog-dev.odisha.gov.in
egov.noc.service.host=https://sujog-dev.odisha.gov.in

#od.mixed-use.enabled=true;


#filestoreservice.beanname=egovMicroServiceStore

filestore.temp.dir=C:\\Temp\\